# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dice', models.CharField(max_length=32)),
                ('character_sheet', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 2, 28, 10, 25, 29, 784419), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 2, 28, 10, 25, 29, 784442))),
            ],
        ),
    ]
