# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='character_sheet',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 11, 20, 54, 417278), editable=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 11, 20, 54, 417306)),
        ),
    ]
