# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 11:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0002_auto_20180228_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_players', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 2, 28, 11, 54, 30, 232538), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 2, 28, 11, 54, 30, 232574))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 11, 54, 30, 231214), editable=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 11, 54, 30, 231256)),
        ),
        migrations.AddField(
            model_name='room',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.GameModel'),
        ),
    ]
