# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20180228_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 11, 14, 23, 43489), editable=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 11, 14, 23, 43516)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 11, 14, 23, 44317), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 11, 14, 23, 44341)),
        ),
    ]
