# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-22 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20180308_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='text_id',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 17, 34, 53, 271647), editable=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 17, 34, 53, 271683)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 17, 34, 53, 272740), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 17, 34, 53, 272765)),
        ),
    ]
