# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-22 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20180322_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 18, 54, 52, 566178), editable=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 18, 54, 52, 566329)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 18, 54, 52, 568514), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='text_id',
            field=models.CharField(default='', editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 18, 54, 52, 568627)),
        ),
    ]
