# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20180322_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='system',
            new_name='game_model',
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 19, 8, 424692), editable=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 19, 8, 424716)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 19, 8, 425253), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 19, 8, 425274)),
        ),
    ]
