# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20180326_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 42, 2, 265949), editable=False),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 42, 2, 265978)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 42, 2, 266920), editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='game_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.GameModel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 10, 42, 2, 266944)),
        ),
    ]
